### PR TITLE
Take care of unicode in Content properties + tests

### PR DESCRIPTION
**Pull request by farirat**
Unicode values in Content properties were not encoded correctly in py2

### CODE REVIEW

**Comment by farirat** [comment]
@esteve can you please review this PR and push a new release ?

**Comment by esteve** [comment]
Thanks!

**Comment by farirat** [comment]
@esteve can you please release on pypi as well ?

**Comment by esteve** [comment]
Done https://pypi.python.org/pypi/txAMQP/0.8.2

**Pull request merged**
